### ISSUE TITLE
feat: add integration tests to pre-push hooks

### ISSUE THREAD

**Issue by JimBarrows** [ErpMicroServices/PeopleAndOrganizationDomain#42]
## Description
Pre-push hooks currently only run unit tests, while CI/CD runs full integration tests with PostgreSQL. This means integration test failures are only caught after pushing, leading to failed CI builds.

## Current State
- Pre-commit hooks run: `./gradlew clean build -x integrationTest`
- CI/CD runs: Full test suite including integration tests with PostgreSQL service

## Proposed Solution
Add a lightweight integration test run to pre-push hooks that:
1. Uses Testcontainers (already configured in the project)
2. Runs only critical integration tests (tagged appropriately)
3. Has a reasonable timeout (5 minutes max)
4. Can be bypassed with `--no-verify` for emergency pushes

## Implementation
Update `.pre-commit-config.yaml` to add:
```yaml
- id: gradle-integration-tests-push
  name: Gradle Integration Tests (pre-push)
  entry: |
    #!/bin/bash
    echo "Running integration tests..."
    ./gradlew integrationTest --no-daemon
  language: script
  stages: [push]
  pass_filenames: false
  always_run: true
```

## Benefits
- Catch database-related issues before push
- Reduce CI/CD failures
- Improve code quality
- Earlier feedback on integration issues

## Acceptance Criteria
- [ ] Integration tests run on pre-push
- [ ] Tests use Testcontainers for database
- [ ] Reasonable timeout configured
- [ ] Clear skip instructions documented
- [ ] Performance impact is acceptable (<5 minutes)
