### ISSUE TITLE
feat: add SpotBugs static analysis to pre-push hooks

### ISSUE THREAD

**Issue by JimBarrows** [ErpMicroServices/PeopleAndOrganizationDomain#43]
## Description
CI/CD runs SpotBugs static analysis to detect potential bugs, but this is not included in pre-commit hooks. Adding SpotBugs to pre-push would catch bugs earlier in the development cycle.

## Current State
- CI/CD: Runs SpotBugs on both main and test code
- Pre-commit: No static bug analysis
- Issues only discovered after push, causing CI failures

## Proposed Solution
Add SpotBugs execution to pre-push hooks:
1. Run SpotBugs on changed modules only (performance optimization)
2. Report findings in a developer-friendly format
3. Fail the push if high-priority bugs are found
4. Allow bypass with `--no-verify` when needed

## Implementation
Add to `.pre-commit-config.yaml`:
```yaml
- id: gradle-spotbugs-push
  name: SpotBugs Static Analysis (pre-push)
  entry: |
    #!/bin/bash
    echo "Running SpotBugs analysis..."
    ./gradlew spotbugsMain spotbugsTest --no-daemon
  language: script
  stages: [push]
  pass_filenames: false
  always_run: true
```

## Configuration Notes
- SpotBugs is already configured in the project with `ignoreFailures = true`
- Consider making it fail on high-priority findings only for pre-push
- Current config includes findsecbugs plugin for security analysis

## Benefits
- Early detection of potential bugs
- Security issue detection (via findsecbugs)
- Consistent code quality
- Reduced CI/CD failures

## Acceptance Criteria
- [ ] SpotBugs runs on pre-push for both main and test code
- [ ] Clear reporting of findings
- [ ] Fails on high-priority bugs only
- [ ] Performance is acceptable (<2 minutes)
- [ ] Can be bypassed when necessary
