### ISSUE TITLE
feat: add test coverage validation to pre-push hooks

### ISSUE THREAD

**Issue by JimBarrows** [ErpMicroServices/PeopleAndOrganizationDomain#44]
## Description
CI/CD enforces 80% minimum test coverage using JaCoCo, but pre-commit hooks don't validate coverage. This leads to coverage regressions being caught only after push.

## Current State
- CI/CD: Runs `jacocoTestCoverageVerification` with 80% minimum
- Pre-commit: No coverage measurement or validation
- Coverage reports generated but not validated locally

## Proposed Solution
Add coverage validation to pre-push hooks:
1. Run tests with JaCoCo coverage
2. Validate against 80% threshold
3. Provide clear coverage report
4. Allow module-specific overrides if needed

## Implementation
Add to `.pre-commit-config.yaml`:
```yaml
- id: gradle-coverage-check-push
  name: Test Coverage Validation (pre-push)
  entry: |
    #\!/bin/bash
    echo "Validating test coverage..."
    ./gradlew test jacocoTestReport jacocoTestCoverageVerification --no-daemon
    
    # Also generate a summary for developer
    echo "Coverage report available at:"
    echo "  api/build/reports/jacoco/test/html/index.html"
  language: script
  stages: [push]
  pass_filenames: false
  always_run: true
```

## JaCoCo Configuration
Project already has JaCoCo configured with:
- 80% minimum coverage threshold
- Exclusions for DTOs, configs, generated code
- HTML and XML report generation

## Benefits
- Prevent coverage regressions before push
- Maintain code quality standards
- Earlier feedback on test completeness
- Align local development with CI/CD

## Acceptance Criteria
- [ ] Coverage validation runs on pre-push
- [ ] Uses same 80% threshold as CI/CD
- [ ] Generates readable coverage report
- [ ] Clear error messages when threshold not met
- [ ] Performance is acceptable
- [ ] Can be bypassed with `--no-verify`
