### ISSUE TITLE
feat: add security dependency scan to pre-push hooks

### ISSUE THREAD

**Issue by JimBarrows** [ErpMicroServices/PeopleAndOrganizationDomain#45]
## Description
CI/CD runs security scans using Trivy and OWASP Dependency Check, but pre-commit only has basic secret detection. Adding dependency security scanning to pre-push would catch vulnerabilities before they reach the repository.

## Current State
- CI/CD: Runs Trivy filesystem scan and OWASP Dependency Check (currently disabled)
- Pre-commit: Only detect-secrets for credential scanning
- Security vulnerabilities only found after push

## Proposed Solution
Add lightweight security scanning to pre-push:
1. Run OWASP Dependency Check on changed modules
2. Quick scan mode for performance
3. Fail on high/critical vulnerabilities only
4. Provide clear vulnerability report

### Option 1: Enable OWASP Dependency Check (already configured)
```yaml
- id: gradle-security-scan-push
  name: OWASP Dependency Check (pre-push)
  entry: |
    #!/bin/bash
    echo "Running security dependency scan..."
    # Note: Currently skip=true in build.gradle, would need to be conditional
    ./gradlew dependencyCheckAnalyze --no-daemon -PdependencyCheck.skip=false
  language: script
  stages: [push]
  pass_filenames: false
  always_run: true
```

### Option 2: Add npm audit for UI components
```yaml
- id: npm-security-audit-push
  name: NPM Security Audit (pre-push)
  entry: |
    #!/bin/bash
    if [ -d "ui-components" ]; then
      echo "Running npm security audit..."
      cd ui-components && npm audit --audit-level=high
    fi
  language: script
  stages: [push]
  pass_filenames: false
  files: ^ui-components/
```

## Considerations
- OWASP check can be slow on first run (downloads CVE database)
- Consider caching CVE database locally
- May need to adjust severity thresholds for practicality

## Benefits
- Early detection of vulnerable dependencies
- Prevent security issues from entering codebase
- Compliance with security best practices
- Reduced security debt

## Acceptance Criteria
- [ ] Security scan runs on pre-push
- [ ] Fails on high/critical vulnerabilities
- [ ] Clear reporting of vulnerabilities found
- [ ] Reasonable performance (<3 minutes after initial setup)
- [ ] Handles both Java and JavaScript dependencies
- [ ] Can be bypassed when necessary
