### ISSUE TITLE
feat: add UI component tests to pre-commit hooks

### ISSUE THREAD

**Issue by JimBarrows** [ErpMicroServices/PeopleAndOrganizationDomain#46]
## Description
CI/CD runs full UI component testing including tests, linting, and builds, but pre-commit only runs ESLint. This misses test failures and build issues until after commit.

## Current State
- CI/CD: Runs `npm test`, `npm run build`, and coverage reporting
- Pre-commit: Only ESLint for JavaScript/TypeScript files
- UI test failures and build issues caught late

## Proposed Solution
Enhance UI-related pre-commit hooks:
1. Run UI unit tests on commit (not just linting)
2. Validate build on push
3. Check for common React/Vite issues
4. Ensure component coverage meets standards

## Implementation
Update `.pre-commit-config.yaml`:

### For commit stage (lightweight):
```yaml
- id: ui-component-tests
  name: UI Component Tests
  entry: |
    #!/bin/bash
    if [ -d "ui-components" ] && [ -f "ui-components/package.json" ]; then
      echo "Running UI component tests..."
      cd ui-components && npm test -- --run --reporter=verbose
    fi
  language: script
  pass_filenames: false
  files: ^ui-components/.*\.(js|jsx|ts|tsx)$
```

### For push stage (comprehensive):
```yaml
- id: ui-component-build-push
  name: UI Component Build Validation (pre-push)
  entry: |
    #!/bin/bash
    if [ -d "ui-components" ] && [ -f "ui-components/package.json" ]; then
      echo "Building UI components..."
      cd ui-components && npm run build
    fi
  language: script
  stages: [push]
  pass_filenames: false
  files: ^ui-components/
```

## Additional Checks to Consider
- TypeScript type checking (`tsc --noEmit`)
- Bundle size analysis
- Accessibility linting (eslint-plugin-jsx-a11y)

## Benefits
- Catch UI test failures before commit
- Prevent broken builds
- Ensure UI quality matches backend quality
- Faster feedback loop for UI developers

## Acceptance Criteria
- [ ] UI tests run on relevant file changes
- [ ] Build validation on push
- [ ] Clear test output and error messages
- [ ] Performance is reasonable (<1 minute for tests)
- [ ] Skips when no UI changes detected
- [ ] Integrates well with existing ESLint checks
