### ISSUE TITLE
Implement OAuth2 Security with AWS Cognito Integration

### ISSUE THREAD

**Issue by JimBarrows** [ErpMicroServices/PeopleAndOrganizationDomain#7]
## Summary
Implement comprehensive OAuth2 security using AWS Cognito for authentication and authorization, including proper Docker setup for development.

## Background
The application.yml mentions OAuth2 configuration but no security implementation exists. The README shows optional OAuth2 environment variables but the security layer is not implemented.

## Requirements
- Implement Spring Security with OAuth2/JWT support
- Integrate with AWS Cognito for authentication
- Set up role-based access control (RBAC)
- Create local development setup with Docker
- Add proper error handling and logging
- Implement token validation and refresh

## Acceptance Criteria
- [ ] Create SecurityConfig class with OAuth2 configuration
- [ ] Implement JWT token validation
- [ ] Set up AWS Cognito integration
- [ ] Create Docker setup for local Cognito testing (LocalStack or mock)
- [ ] Add role-based authorization annotations
- [ ] Implement proper CORS configuration
- [ ] Add security integration tests
- [ ] Create user management endpoints
- [ ] Add proper error handling for auth failures
- [ ] Document security setup and configuration

## Security Requirements
- All GraphQL endpoints require authentication (except health checks)
- Role-based access: ADMIN, USER, READONLY
- JWT token validation with proper expiration handling
- Secure CORS configuration
- Rate limiting for authentication endpoints
- Audit logging for security events

## Docker Setup Requirements
- LocalStack container for local AWS services testing
- Mock Cognito service for development
- Docker Compose configuration for easy setup
- Environment-specific configurations

## Configuration Structure
```yaml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
      client:
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
```

## Technical Details
- Use Spring Security 6+ with OAuth2 Resource Server
- Implement proper exception handling
- Add security headers (HSTS, CSP, etc.)
- Use method-level security annotations
- Implement custom UserDetails service if needed

## Dependencies
- Docker setup for development environment
- May require GraphQL resolvers to be updated with security annotations

## Definition of Done
- OAuth2 authentication is fully functional
- All endpoints are properly secured
- Integration tests verify security behavior
- Local development works with Docker setup
- Production configuration is documented
- Security audit passes all checks
